// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello World';
//
//   build() {
//     Row() {
//       Column() {
//         Text(this.message)
//           .fontSize(200)
//           .fontWeight(FontWeight.Bold)
//           .onClick(() => {
//             this.message = 'Welcome';
//           })
//       }
//       .width('100%')
//     }
//     .height('100%')
//   }
// }